### ISSUE TITLE
Flawed ?

### ISSUE THREAD

**Issue by Asc2011** [erizocosmico/go-ewah#1]
> var b *Bitmap
> b = New()
> arr := []int64{ 1,5,8,11,15,19,23,30,128 }
> for _, e := range arr { b.Set( e ) }
> for index, e := range arr {		
>   fmt.Println("At index", index, "value is", b.Get(e) )
> }

Exchange the last value=128 with 127 and in the second-loop all lookups return ` true` as one would expect ? Or am i doing smth. stupid :) 

[test at Go-playground](https://play.golang.org/p/CfscHJ9h7fE)

I checked this against the java-version and it returns `true` for both cases 127 and 128, so i guess there is smth. wrong.

**Comment by erizocosmico** [comment]
You’re right, this is a bug in the implementation. Good catch!

**Comment by Asc2011** [comment]
thx, my pleasure - i was trying to do a iterator so that one can walk along the set bits of the Bitmap.
Do you think this is fixable ? Cos' right now i'm pretty much blown away by looking at ~2000-loc of chatty-chatty Java-stuff, that you have already boiled to ~200-loc - nice job btw :) 
I'd really prefer to stay with your concise version - java kills me..
greets Andreas

**Comment by erizocosmico** [comment]
Hey @Asc2011! I found the issue and it should be fixed now in v1.0.1. Thanks for reporting it!

**Comment by asad-awadia** [comment]
@erizocosmico can bits be set in non-increasing order?

**Comment by erizocosmico** [comment]
@asad-awadia no, only in ascending order

**Comment by lemire** [comment]
@erizocosmico Note that it is possible to implement non-increasing setters (although it is not very easy)... we did it in javaewah.

**Comment by erizocosmico** [comment]
@lemire oh, nice to know! Sadly, current implementation in this library does not allow for non-increasing setters
